# -*- coding: utf-8 -*-
"""7 Despliegue-ventas-carga datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cKXCwn0QkHkIE3w0y8bag3zOEMPTN3Um

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler,variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("ventas - despliegue.csv")
#data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de ventas')

# Cargar archivo
uploaded_file = st.file_uploader("Sube el archivo CSV con los datos a predecir",type=["csv"])

#Se valida si el archivo fue cargado
if uploaded_file is None:
    st.stop()

data = pd.read_csv(uploaded_file)
st.dataframe(data.head())

# Boton de predecir
if not st.button("Predecir"):
    st.stop()

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red neuronal, SMV
data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
data_preparada.head()

"""# **Predicciones**

**El modelo presenta un error del 9%**
"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
data['Predicción']=Y_pred
data.head()

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 4%")

#descargar resultados
csv = data.to_csv(index=False).encode("utf-8")

st.download_button(
    label="Descargar resultados",
    data=csv,
    file_name="resultados_prediccion.csv",
    mime="text/csv"
)