# -*- coding: utf-8 -*-
"""7 Despliegue-Ventas OPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1st0e-GXINFS3P9LXGPru6JasBWGogzXF

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-reg.pkl'
modelo, min_max_scaler,variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("ventas - despliegue.csv")
#data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de ventas')


# Cargar archivo
uploaded_file = st.file_uploader(
    "Sube el archivo Excel con los datos a predecir",
    type=["xlsx"]
)

data = pd.read_excel(uploaded_file)

#Se realiza la preparación
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red neuronal, SMV
data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
data['Predicción']=Y_pred
data.head()

data

print("Las predicciones tienen un error del 4%")

#descargar resultados en excel
csv = data.to_csv("predicciones.csv")

st.download_button(
    label="Descargar resultados en Excel",
    data=csv,
    file_name="resultados_prediccion.csv",
    mime="text/csv"
)